### ISSUE TITLE
Repoint HELP to Lumerin.gitbook.io

### ISSUE THREAD

**Issue by LumerinIO** [Lumerin-protocol/WalletDesktop#101]
Currently the HELP link at the bottom of the left navigation bar in the wallet goes to an old edition of the marketplace.  Please update so that it links to the https://lumerin.gitbook.io Gitbook instance

![image](https://user-images.githubusercontent.com/102425763/223549328-0465ee9b-86ce-45a3-ac3d-648d5d17f9b2.png)

**Comment by LumerinIO** [comment]
Exalate commented: GitHub source link is https://github.com/Lumerin-protocol/WalletDesktop/issues/101

**Comment by alex-sandrk** [comment]
closed by https://github.com/Lumerin-protocol/WalletDesktop/pull/106/commits/a8e37b53df53994e97b64da540f7ecd079008da6
