### ISSUE TITLE
contract link out to etherscan is not working in marketplace and buyerhub

### ISSUE THREAD

**Issue by alicexbloq** [Lumerin-protocol/WalletDesktop#147]
1.1.1 lmn MacOS

**Comment by alex-sandrk** [comment]
cant reproduce this issue. Could you please provide some additional info?
1. What behaviour do you see? Just nothing happen on click?
2. Probably some conditions like: wallet was running for a long time
3. Did restart of the wallet fixed the issue?

**Comment by alicexbloq** [comment]
1. Nothing happens after click
2 & 3. downloaded new version of wallet, still same issue
