### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by SergioCk87** [Lumerin-protocol/WalletDesktop#166]
Ver. 1.1.6
Unhandled Promise Rejection
Error: Invalid JSON RPC response: {"size":0,"timeout":0}
    at Object.InvalidResponse (C:/Users/user/AppData/Local/Programs/lumerin-wallet-desktop/resources/app.asar/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at C:/Users/user/AppData/Local/Programs/lumerin-wallet-desktop/resources/app.asar/node_modules/web3-providers-http/lib/index.js:129:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
![IMG_20230427_231755](https://user-images.githubusercontent.com/69136761/234981278-4957cb2c-b3d8-43c4-b226-748fcb4ad932.jpg)

**Comment by abs2023** [comment]
Thanks for reporting this issue.  We have recognized that our API calls from the wallet to Sepolia needed to be optimized and leverage different back-end infrastructure.  An update is being tested and will be released in the next few days that will eliminate issues found in both version 1.1.4 and 1.1.6.  Thank you for your patience as we work through these issues.

**Comment by LumerinIO** [comment]
Thank you very much for your patience!  We have released v1.1.10 (https://lumerin.io/download) or from the GitHub releases page here.  We are seeing much better API behavior and you should no longer see those issues. Please update your installation and open up a new ticket if you see any new issues. Happy Routing!!
