### ISSUE TITLE
Get sLMR not working

### ISSUE THREAD

**Issue by amamood** [Lumerin-protocol/WalletDesktop#168]
Hi there, I have been able to get sETH but not and sLMR

**Lumerin wallet** 

Lumerin wallet / get tokens / captcha validation failed 

**Lumerin Faucet**

Metamask/https://faucet.lumerin.io/ 0.05 sETH received / no sLMR (sepolia received)

Perhaps I'm not seeting the sLMR in my wallet. 
Can you please post the contract address for the sLMR so I can add it as a custom token in my Metamask? 
thankyou

**Comment by abs2023** [comment]
We found some issues with the faucet (both security and process related).  They have been fixed and the faucet was redeployed yesterday at 5:30 pm EST.  You should be able to get test tokens today with the new release.  I will close this issue as we believe it has been resolved.  If you are still having problems afterward, please create a new issue.  
Thank you!
