### ISSUE TITLE
Wallet v1.1.6 update always popping out invalid json rpc response error

### ISSUE THREAD

**Issue by singoku** [Lumerin-protocol/WalletDesktop#169]
invalid json rpc response make it impossible to sync anything

**Comment by kachers** [comment]
I have the same issue. Using linux OS.

**Comment by artmdrbnv** [comment]
The same using MacOs

**Comment by LumerinIO** [comment]
Thank you very much for your patience!  We have released v1.1.10 (https://lumerin.io/download) or from the GitHub releases page here.  We are seeing much better API behavior and you should no longer see those issues. Please update your installation and open up a new ticket if you see any new issues. Happy Routing!!
