### ISSUE TITLE
An issue with getting the test tokens 

### ISSUE THREAD

**Issue by Cheeeeek1** [Lumerin-protocol/WalletDesktop#175]
![16829825794014581531807063272238](https://user-images.githubusercontent.com/131983210/235546914-2bbfdd8c-d9a6-4819-ba7c-f66ca961f91d.jpg)
I got this when I was trying to get the test tokens from Lumerin testnet Faucet and also from LMR wallet. Can you please assist me with this? Thanks

**Comment by abs2023** [comment]
We found some issues with the faucet (both security and process related).  They have been fixed and the faucet was redeployed yesterday at 5:30 pm EST.  You should be able to get test tokens today with the new release.  Thank you!
