### ISSUE TITLE
Spelling error in Purchase Hashpower form

### ISSUE THREAD

**Issue by codywall** [Lumerin-protocol/WalletDesktop#84]
"Mining Poll" should be changed to "Mining Pool"

<img width="449" alt="Screen Shot 2023-02-07 at 4 34 25 PM" src="https://user-images.githubusercontent.com/22305037/217380176-e533bf3d-2bca-4ed8-a8a5-d437d6caebab.png">

**Comment by LumerinIO** [comment]
Exalate commented: GitHub source link is https://github.com/Lumerin-protocol/WalletDesktop/issues/84

**Comment by bohdan-titan** [comment]
Fixed as part
